#!/usr/bin/env python
from subprocess import check_call
import xml.dom.minidom as minidom
import sys, os

if len(sys.argv) < 3:
	print "please provide: 1) one or more input files and 2) an output file"
	print sys.argv
	sys.exit(-1)

def version_from_pom():
	pom = minidom.parse('pom.xml')
	project = pom.getElementsByTagName('project')[0]
	top_level_version_list = [n for n in project.childNodes if n.nodeType == 1 and n.tagName == 'version']
	assert len(top_level_version_list) == 1
	non_null_text_list = [x for x in top_level_version_list[0].childNodes if x.nodeType == 3 and len(x.nodeValue.strip()) > 0]
	assert len(non_null_text_list) == 1
	return non_null_text_list[0].nodeValue

version = version_from_pom()
jar = 'target/concrete-agiga-' + version + '.jar'
deps = 'target/concrete-agiga-' + version + '-jar-with-dependencies.jar'
if not (os.path.exists(jar) and os.path.exists(deps)):
	print "COMPILING version", version
	check_call(['mvn', 'clean'])
	check_call(['mvn', 'package'])
	check_call(['mvn', 'assembly:single'])
if not (os.path.exists(jar) and os.path.exists(deps)):
	print "couldn't find %s and %s jars" % (jar, deps)
	print 'make sure you have the correct version number'
	sys.exit(-2)

print "RUNNING..."
print sys.argv[1], "=>", sys.argv[-1]
args = ['/usr/bin/time', 'java', '-ea', '-classpath', jar+':'+deps, 'edu.jhu.hlt.concrete.agiga.AgigaConverter']
args.append(sys.argv[-1])
args.append("false")
for f in sys.argv[1:-1]:
	args.append(f)
print ' '.join(args)
check_call(args)


