#!/usr/bin/env python
from subprocess import check_call
import sys, os

if len(sys.argv) < 3:
	print "please provide: 1) one or more input files and 2) an output file"
	sys.exit(-1)

version = '2.0.0-SNAPSHOT'
jar = 'target/concrete-agiga-' + version + '.jar'
deps = 'target/concrete-agiga-' + version + '-jar-with-dependencies.jar'
if not (os.path.exists(jar) and os.path.exists(deps)):
	print "COMPILING"
	check_call(['mvn', 'clean'])
	check_call(['mvn', 'package'])
	check_call(['mvn', 'assembly:single'])
if not (os.path.exists(jar) and os.path.exists(deps)):
	print "couldn't find %s and %s jars" % (jar, deps)
	print 'make sure you have the correct version number'
	sys.exit(-2)

print "RUNNING..."
print sys.argv[1], "=>", sys.argv[-1]
args = ['/usr/bin/time', 'java', '-ea', '-classpath', jar+':'+deps, 'edu.jhu.hlt.concrete.agiga.AgigaConverter']
for f in sys.argv[1:-1]:
	args.append(f)
args.append(sys.argv[-1])
check_call(args)


